version: '3.4'

name: masstransit-client

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  seq:
    container_name: Seq
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
      - WEBSITES_PORT=80:5341

  masstransit.client.api:
    container_name: masstransit.client.api
    image: masstransit.client.api:latest
    depends_on:
      - rabbitmq
      - seq
    build: 
      dockerfile: src/MassTransitClient.API/Dockerfile
    ports:
      - "80:80"
      - "443:443"

 
